[package]
name = "assemble_app"
version = "0.1.0"
authors = ["Kyle <me@khanson.io>"]
edition = "2018"

[dependencies]
wapc-guest = "0.4.0"
rmp-serde = "0.15.0"
serde = "1.0.118"
serde_derive = "1.0.118"
